name: Enforce PR Title
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - opened

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
